"""Generate a SAFE project health report in JSON and Markdown."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.branding_check import run_branding_check
from scripts.security_self_check import run_self_check


SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".pytest_tmp",
    "agent/.venv-build",
    "build",
    "dist",
}


@dataclass(frozen=True, slots=True)
class HealthReport:
    total_tests_static: int
    skipped_tests_static: int
    modules_count: int
    routes_count: int
    templates_count: int
    docs_count: int
    security_checks_ok: bool
    architecture_coverage: dict[str, bool]
    todo_fixme_count: int
    deprecated_references: int
    branding_consistency: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def build_health_report(root: str | Path = ".") -> HealthReport:
    base = Path(root)
    py_files = list(_iter_files(base, {".py"}))
    docs = list(_iter_files(base, {".md"}))
    templates = list((base / "templates").rglob("*.html")) if (base / "templates").exists() else []
    text_files = list(_iter_files(base, {".py", ".html", ".css", ".js", ".md", ".yml", ".yaml", ".txt"}))
    branding = run_branding_check(base)
    self_check = run_self_check(base)
    return HealthReport(
        total_tests_static=_count_tests(base / "tests"),
        skipped_tests_static=_count_skips(base / "tests"),
        modules_count=len(py_files),
        routes_count=_count_routes(base / "app.py") + _count_routes_in_dir(base / "routes"),
        templates_count=len([path for path in templates if _not_skipped(path.relative_to(base).as_posix())]),
        docs_count=len(docs),
        security_checks_ok=bool(self_check.get("ok")),
        architecture_coverage=_architecture_coverage(base),
        todo_fixme_count=_count_terms(text_files, ("TODO", "FIXME")),
        deprecated_references=_count_terms(text_files, ("deprecated", "legacy-only")),
        branding_consistency=branding["summary"],
    )


def write_reports(report: HealthReport, root: str | Path = ".") -> dict[str, str]:
    base = Path(root)
    json_path = base / "project_health_report.json"
    md_path = base / "PROJECT_HEALTH_REPORT.md"
    json_path.write_text(json.dumps(report.to_dict(), indent=2, sort_keys=True), encoding="utf-8")
    md_path.write_text(_to_markdown(report), encoding="utf-8")
    return {"json": str(json_path), "markdown": str(md_path)}


def _to_markdown(report: HealthReport) -> str:
    coverage_lines = "\n".join(
        f"- {name}: {'covered' if value else 'missing'}"
        for name, value in sorted(report.architecture_coverage.items())
    )
    return f"""# SAFE Project Health Report

Generated by `scripts/project_health_report.py`.

## Quality Snapshot

- Static test count: {report.total_tests_static}
- Static skipped tests markers: {report.skipped_tests_static}
- Python modules: {report.modules_count}
- Flask routes: {report.routes_count}
- Templates: {report.templates_count}
- Markdown docs: {report.docs_count}
- Security self-check OK: {str(report.security_checks_ok).lower()}
- TODO/FIXME count: {report.todo_fixme_count}
- Deprecated references: {report.deprecated_references}
- Branding blockers: {report.branding_consistency.get('blockers', 0)}
- Branding warnings: {report.branding_consistency.get('warnings', 0)}

## Architecture Coverage

{coverage_lines}

## Release Interpretation

SAFE is in enterprise-preview readiness when tests, pentest audit, release check,
and security self-check pass together. This report is a static project health
snapshot and should be used together with `python scripts/release_check.py`.
"""


def _iter_files(base: Path, suffixes: set[str]) -> list[Path]:
    files: list[Path] = []
    for path in base.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in suffixes:
            continue
        rel = path.relative_to(base).as_posix()
        if _not_skipped(rel):
            files.append(path)
    return files


def _not_skipped(rel: str) -> bool:
    parts = rel.split("/")
    if any(part.startswith("tenant-isolation-") for part in parts):
        return False
    if any(part.startswith(".tmp") or part.startswith("ci_pytest") for part in parts):
        return False
    return not any(skip in {parts[0], "/".join(parts[:2])} for skip in SKIP_DIRS)


def _count_tests(tests_dir: Path) -> int:
    if not tests_dir.exists():
        return 0
    total = 0
    for path in tests_dir.rglob("test_*.py"):
        if _not_skipped(path.as_posix()):
            total += len(re.findall(r"^\s*def\s+test_", path.read_text(encoding="utf-8", errors="ignore"), re.MULTILINE))
    return total


def _count_skips(tests_dir: Path) -> int:
    if not tests_dir.exists():
        return 0
    count = 0
    for path in tests_dir.rglob("test_*.py"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        count += text.count("@pytest.mark.skip") + text.count("pytest.skip(")
    return count


def _count_routes(path: Path) -> int:
    if not path.exists():
        return 0
    return len(re.findall(r"@(?:app|bp)\.route\(", path.read_text(encoding="utf-8", errors="ignore")))


def _count_routes_in_dir(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(_count_routes(item) for item in path.rglob("*.py"))


def _count_terms(paths: list[Path], terms: tuple[str, ...]) -> int:
    total = 0
    for path in paths:
        text = path.read_text(encoding="utf-8", errors="ignore")
        total += sum(text.count(term) for term in terms)
    return total


def _architecture_coverage(base: Path) -> dict[str, bool]:
    required = {
        "agent": "agent/agent.py",
        "central_api": "app.py",
        "xdr_pipeline": "xdr/pipeline.py",
        "security_data_platform": "schema/canonical_event.py",
        "response_policy": "xdr/policy_engine.py",
        "soc_operations": "xdr/case_management.py",
        "operational_reliability": "xdr/event_bus.py",
        "docs": "docs/ARCHITECTURE.md",
        "ci": ".github/workflows/ci.yml",
    }
    return {name: (base / rel).exists() for name, rel in required.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SAFE project health report.")
    parser.add_argument("--root", default=".")
    parser.add_argument("--json-only", action="store_true")
    args = parser.parse_args()
    report = build_health_report(args.root)
    paths = write_reports(report, args.root)
    if args.json_only:
        print(json.dumps(report.to_dict(), indent=2, sort_keys=True))
    else:
        print(f"Wrote {paths['markdown']}")
        print(f"Wrote {paths['json']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
